"""Add PLACSP fields

Revision ID: ac1ba32b6d3b
Revises: 002_google_sheets
Create Date: 2025-11-28 16:15:46.264882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1ba32b6d3b'
down_revision: Union[str, Sequence[str], None] = '002_google_sheets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_history_created_at'), 'webhook_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_history_grant_id'), 'webhook_history', ['grant_id'], unique=False)
    op.create_index(op.f('ix_webhook_history_id'), 'webhook_history', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_history_next_retry_at'), 'webhook_history', ['next_retry_at'], unique=False)
    op.add_column('grants', sa.Column('source', sa.String(), nullable=False))
    op.add_column('grants', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('grants', sa.Column('department', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('section', sa.String(), nullable=True))
    op.add_column('grants', sa.Column('publication_date', sa.DateTime(), nullable=True))
    op.add_column('grants', sa.Column('captured_at', sa.DateTime(), nullable=True))
    op.add_column('grants', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.add_column('grants', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('grants', sa.Column('sent_to_n8n', sa.Boolean(), nullable=True))
    op.add_column('grants', sa.Column('sent_to_n8n_at', sa.DateTime(), nullable=True))
    op.add_column('grants', sa.Column('pdf_url', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('html_url', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('xml_url', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('pdf_processed', sa.Boolean(), nullable=True))
    op.add_column('grants', sa.Column('pdf_content_text', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('pdf_content_markdown', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('bdns_code', sa.String(), nullable=True))
    op.add_column('grants', sa.Column('bdns_id', sa.Integer(), nullable=True))
    op.add_column('grants', sa.Column('boe_id', sa.String(), nullable=True))
    op.add_column('grants', sa.Column('placsp_folder_id', sa.String(), nullable=True))
    op.add_column('grants', sa.Column('contract_type', sa.String(), nullable=True))
    op.add_column('grants', sa.Column('cpv_codes', sa.JSON(), nullable=True))
    op.add_column('grants', sa.Column('tender_value_estimated', sa.Float(), nullable=True))
    op.add_column('grants', sa.Column('budget_amount', sa.Float(), nullable=True))
    op.add_column('grants', sa.Column('application_start_date', sa.DateTime(), nullable=True))
    op.add_column('grants', sa.Column('application_end_date', sa.DateTime(), nullable=True))
    op.add_column('grants', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('grants', sa.Column('is_nonprofit', sa.Boolean(), nullable=True))
    op.add_column('grants', sa.Column('nonprofit_confidence', sa.Float(), nullable=True))
    op.add_column('grants', sa.Column('beneficiary_types', sa.JSON(), nullable=True))
    op.add_column('grants', sa.Column('sectors', sa.JSON(), nullable=True))
    op.add_column('grants', sa.Column('regions', sa.JSON(), nullable=True))
    op.add_column('grants', sa.Column('instruments', sa.JSON(), nullable=True))
    op.add_column('grants', sa.Column('funds', sa.JSON(), nullable=True))
    op.add_column('grants', sa.Column('convocatoria_type', sa.String(), nullable=True))
    op.add_column('grants', sa.Column('purpose', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('regulatory_base_url', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('electronic_office', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('state_aid_number', sa.String(), nullable=True))
    op.add_column('grants', sa.Column('state_aid_url', sa.Text(), nullable=True))
    op.add_column('grants', sa.Column('bdns_documents', sa.JSON(), nullable=True))
    op.add_column('grants', sa.Column('bdns_last_updated', sa.DateTime(), nullable=True))
    op.add_column('grants', sa.Column('enriched', sa.Boolean(), nullable=True))
    op.add_column('grants', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('grants', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('grants', sa.Column('strategic_value', sa.Float(), nullable=True))
    op.add_column('grants', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    op.add_column('grants', sa.Column('analysis_timestamp', sa.DateTime(), nullable=True))
    op.alter_column('grants', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('grants', 'google_sheets_exported',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_grants_application_end_date'), 'grants', ['application_end_date'], unique=False)
    op.create_index(op.f('ix_grants_bdns_code'), 'grants', ['bdns_code'], unique=False)
    op.create_index(op.f('ix_grants_boe_id'), 'grants', ['boe_id'], unique=False)
    op.create_index(op.f('ix_grants_budget_amount'), 'grants', ['budget_amount'], unique=False)
    op.create_index(op.f('ix_grants_id'), 'grants', ['id'], unique=False)
    op.create_index(op.f('ix_grants_is_nonprofit'), 'grants', ['is_nonprofit'], unique=False)
    op.create_index(op.f('ix_grants_placsp_folder_id'), 'grants', ['placsp_folder_id'], unique=False)
    op.create_index(op.f('ix_grants_source'), 'grants', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grants_source'), table_name='grants')
    op.drop_index(op.f('ix_grants_placsp_folder_id'), table_name='grants')
    op.drop_index(op.f('ix_grants_is_nonprofit'), table_name='grants')
    op.drop_index(op.f('ix_grants_id'), table_name='grants')
    op.drop_index(op.f('ix_grants_budget_amount'), table_name='grants')
    op.drop_index(op.f('ix_grants_boe_id'), table_name='grants')
    op.drop_index(op.f('ix_grants_bdns_code'), table_name='grants')
    op.drop_index(op.f('ix_grants_application_end_date'), table_name='grants')
    op.alter_column('grants', 'google_sheets_exported',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('grants', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('grants', 'analysis_timestamp')
    op.drop_column('grants', 'notification_sent')
    op.drop_column('grants', 'strategic_value')
    op.drop_column('grants', 'priority_score')
    op.drop_column('grants', 'priority')
    op.drop_column('grants', 'enriched')
    op.drop_column('grants', 'bdns_last_updated')
    op.drop_column('grants', 'bdns_documents')
    op.drop_column('grants', 'state_aid_url')
    op.drop_column('grants', 'state_aid_number')
    op.drop_column('grants', 'electronic_office')
    op.drop_column('grants', 'regulatory_base_url')
    op.drop_column('grants', 'purpose')
    op.drop_column('grants', 'convocatoria_type')
    op.drop_column('grants', 'funds')
    op.drop_column('grants', 'instruments')
    op.drop_column('grants', 'regions')
    op.drop_column('grants', 'sectors')
    op.drop_column('grants', 'beneficiary_types')
    op.drop_column('grants', 'nonprofit_confidence')
    op.drop_column('grants', 'is_nonprofit')
    op.drop_column('grants', 'is_open')
    op.drop_column('grants', 'application_end_date')
    op.drop_column('grants', 'application_start_date')
    op.drop_column('grants', 'budget_amount')
    op.drop_column('grants', 'tender_value_estimated')
    op.drop_column('grants', 'cpv_codes')
    op.drop_column('grants', 'contract_type')
    op.drop_column('grants', 'placsp_folder_id')
    op.drop_column('grants', 'boe_id')
    op.drop_column('grants', 'bdns_id')
    op.drop_column('grants', 'bdns_code')
    op.drop_column('grants', 'pdf_content_markdown')
    op.drop_column('grants', 'pdf_content_text')
    op.drop_column('grants', 'pdf_processed')
    op.drop_column('grants', 'xml_url')
    op.drop_column('grants', 'html_url')
    op.drop_column('grants', 'pdf_url')
    op.drop_column('grants', 'sent_to_n8n_at')
    op.drop_column('grants', 'sent_to_n8n')
    op.drop_column('grants', 'relevance_score')
    op.drop_column('grants', 'processed_at')
    op.drop_column('grants', 'captured_at')
    op.drop_column('grants', 'publication_date')
    op.drop_column('grants', 'section')
    op.drop_column('grants', 'department')
    op.drop_column('grants', 'title')
    op.drop_column('grants', 'source')
    op.drop_index(op.f('ix_webhook_history_next_retry_at'), table_name='webhook_history')
    op.drop_index(op.f('ix_webhook_history_id'), table_name='webhook_history')
    op.drop_index(op.f('ix_webhook_history_grant_id'), table_name='webhook_history')
    op.drop_index(op.f('ix_webhook_history_created_at'), table_name='webhook_history')
    op.drop_table('webhook_history')
    # ### end Alembic commands ###
